name: loopme
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  emoji_picker_flutter: ^2.2.0
  flutter_launcher_icons: ^0.14.3
  audioplayers: ^6.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lup.jpg"
flutter:
  uses-material-design: true

  assets:
    - assets/sounds/A.mp3
    - assets/sounds/B.mp3
    - assets/sounds/C.mp3
    - assets/sounds/D.mp3
    - assets/sounds/E.mp3
    - assets/sounds/F.mp3
    - assets/sounds/G.mp3
    - assets/sounds/H.mp3
    - assets/sounds/I.mp3
    - assets/sounds/J.mp3
    - assets/sounds/K.mp3
    - assets/sounds/L.mp3
    - assets/sounds/M.mp3
    - assets/sounds/N.mp3
    - assets/sounds/O.mp3
    - assets/sounds/P.mp3
    - assets/sounds/Q.mp3
    - assets/sounds/R.mp3
    - assets/sounds/S.mp3
    - assets/sounds/T.mp3
    - assets/sounds/U.mp3
    - assets/sounds/V.mp3
    - assets/sounds/W.mp3
    - assets/sounds/X.mp3
    
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
